(setq user-init-file "E:/Cadence/SPB_Data")
(setq user-emacs-directory "D:/Documents/Programming/emacshome")
(setq default-directory "D:/Documents/Programming/emacshome")
(setenv "HOME" "D:/Documents/Programming/emacshome")
(load user-init-file)